janhq/cortex.so

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/discussion-thread.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/epic-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/auto-assign-author.yml
- .github/workflows/auto-label-conventional-commits.yaml
- .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
- .github/workflows/docs.yml
> Add CICD cortex docs

- package.json
- src/components/typeWriterWffect.tsx
- src/pages/index.tsx
- yarn.lock
> chore: update landing page

- docusaurus.config.ts
- package.json
- ImplementScalar API Reference feature
- Closes #
- Closes #
> feat(scalar): Scalar implementation

- docs/cli/chat.md
- docs/cli/cortex.md
- docs/cli/embeddings.mdx
- docs/cli/init.md
- docs/cli/kill.md
- docs/cli/models/download.md
- docs/cli/models/get.md
- docs/cli/models/index.md
- docs/cli/models/list.md
- docs/cli/models/remove.md
- docs/cli/models/start.md
- docs/cli/models/stop.md
- docs/cli/models/update.md
- docs/cli/presets.mdx
- docs/cli/pull.md
- docs/cli/run.md
- docs/cli/serve.md
- docs/installation/windows.mdx
- docusaurus.config.ts
- sidebars.ts
- static/openapi/jan.json
- Update the CLI command and the API reference
- Closes https://github.com/janhq/cortex-web/issues/23
- Closes https://github.com/janhq/cortex-web/issues/21
- Closes https://github.com/janhq/cortex-web/issues/25
- Closes https://github.com/janhq/cortex-web/issues/22
> docs: Update the CLI command and the API reference

- docs/cli/chat.md
- docs/cli/cortex.md
- docs/cli/embeddings.mdx
- docs/cli/init.md
- docs/cli/presets.mdx
- docs/cli/run.md
- docs/installation/linux.mdx
- docs/installation/mac.mdx
- docs/installation/windows.mdx
- docs/server.mdx
- docusaurus.config.ts
- src/components/OAICoverage/index.tsx
- Make the header consistent and Update the cortex init page
- Closes https://github.com/janhq/cortex-web/issues/32
- Closes https://github.com/janhq/cortex-web/issues/31
> docs: Make the header consistent and Update the cortex init page

- .github/workflows/docs.yml
- docusaurus.config.ts
- src/components/OAICoverage/index.tsx
> feat: update daily fetch coverage

- .github/workflows/docs.yml
- docusaurus.config.ts
> fix: update CI event schedule

- docs/embeddings.mdx
- Update the links in the embeddings page
- Closes #
- Closes #
> docs: Update the embeddings page

- docs/architecture.md
- docs/cli/benchmark.mdx
- docs/cli/chat.md
- docs/cli/cortex.md
- docs/cli/embeddings.mdx
- docs/cli/init.md
- docs/cli/kill.md
- docs/cli/models/download.md
- docs/cli/models/get.md
- docs/cli/models/index.md
- docs/cli/models/list.md
- docs/cli/models/remove.md
- docs/cli/models/start.md
- docs/cli/models/stop.md
- docs/cli/models/update.md
- docs/cli/presets.mdx
- docs/cli/pull.md
- docs/cli/run.md
- docs/cli/serve.md
- sidebars.ts
- Update the cli and architecture docs
- Closes https://github.com/janhq/cortex-web/issues/26
- Closes #
> docs: Update the cli and architecture docs

- docs/overview.md
- docs/quickstart.md
- docs/server.mdx
> fix: quickstart

- docs/cortex-llamacpp.md
- docs/cortex-onnx.mdx
- docs/cortex-tensorrt-llm.mdx
- docs/model-operations.mdx
- docs/quickstart.md
- sidebars.ts
- quickstart updates
- cortex.tensorrtllm
- Closes #
- Closes #
> docs: update quickstart and cortex.tensorrtllm

- docs/cli/pull.md
- docs/installation/linux.mdx
- docs/installation/mac.mdx
- docs/installation/windows.mdx
- docs/quickstart.md
- static/openapi/jan.json
- Add the installation using Brew method
- update the json file
- Closes #
- Closes #
> Add the installation using Brew method and update the json file

- static/openapi/jan.json
- Update the JSON file
- Closes #
- Closes #
> Update the JSON file

- static/openapi/jan.json
- Update JSON file
- Closes #
- Closes #
> Update JSON file

- static/openapi/jan.json
- add example for chat completions
- Closes #
- Closes #
> add example

- docs/ts-library.md
- Updated the TS library page
- Closes https://github.com/janhq/cortex-web/issues/52
- Closes #
> Updated the TS library page

- docs/benchmark.mdx
- docs/embeddings.mdx
- sidebars.ts
- Update the Benchmark page
- Closes https://github.com/janhq/cortex-web/issues/28
- Closes #
> Update the Benchmark page

- docusaurus.config.ts
- fix algolia search no result 
- Closes #
- Closes #
> fix: algolia search no result

- static/huggingface/hub.json
> feat: Create hub.json for model info

- .env.example
- docusaurus.config.ts
- static/js/gtag.js
> feat: setup google tag analytic

- docs/chat-completions.mdx
- docs/cli/pull.md
- docs/curated-models.mdx
- static/openapi/jan.json
- Added the ONNX runtime and also revamp the curated models page
- Closes #
- Closes #
> Added the ONNX runtime and also revamp the curated models page

- src/containers/Homepage/OAIReplacement/index.tsx
> fix: added badge coming soon

- src/containers/Homepage/About/index.tsx
- src/containers/Homepage/GettingStartedSection/index.tsx
- src/containers/Homepage/OAIReplacement/index.tsx
- automerge for me pls
- Closes #
- Closes #
> chore: copy fixes

- docs/telemetry-export.mdx
- docs/telemetry.mdx
- sidebars.ts
- Add telemetry export page
- Move the export telemetry section from Architecture  > Telemetry to Capabilities > Telemetry
- Closes #
- Closes #
> docs: telemetry export page

- src/containers/Homepage/HeroSection/index.tsx
- src/pages/models.tsx
> fix: remove badge tensorrt from llama3

- docusaurus.config.ts
- src/components/SocialNavbar/index.tsx
> fix: missing link url

- docs/telemetry-export.mdx
- Update telemetry export env name to CORTEX_EXPORTER_OLTP_ENDPOINT
- Closes #
- Closes #
> docs: update telemetry export env name

- src/containers/Homepage/Download/CardDownload.tsx
> fix: update label linux package

- docs/benchmarking-architecture.mdx
- docs/benchmarking.mdx
- docs/telemetry-architecture.mdx
- Update the architecture page
- Closes #
- Closes #
> Update the architecture page

- docs/architecture.md
- docs/cli/benchmark.mdx
- docs/cli/chat.md
- docs/cli/configs/get.mdx
- docs/cli/embeddings.mdx
- docs/cli/engines/get.mdx
- docs/cli/init.md
- docs/cli/models/download.md
- docs/cli/models/get.md
- docs/cli/models/remove.md
- docs/cli/models/start.md
- docs/cli/models/stop.md
- docs/cli/models/update.md
- docs/cli/pull.md
- docs/cli/run.md
- docs/model-operations.mdx
- docs/requirements.mdx
- Update the requirements and cli docs
- Closes #
- Closes #
> Update the requirements and cli docs

- static/huggingface/hub.json
> chore: remove logo from hub.json

- src/components/OAICoverage/index.tsx
> feat: update style OAI coverage chart

- package.json
- src/components/CopyCommand/index.tsx
- src/components/Select/index.tsx
- src/containers/Homepage/HeroSection/index.tsx
- src/hooks/useClipboard.ts
- src/pages/models.tsx
- tailwind.config.ts
- yarn.lock
> feat: cortex built in models

- docs/cli/benchmark.mdx
- static/openapi/jan.json
- Update the benchmark CLI and JSON file
- Closes #
- Closes #
> Update the benchmark CLI and JSON file

- docs/cli/configs/get.mdx
- docs/cli/configs/list.mdx
- docs/cli/engines/get.mdx
- docs/cli/engines/list.mdx
- docs/cli/models/get.md
- docs/server.mdx
- Update cortex server
- Closes #
- Closes #
> Update cortex server

- src/containers/Homepage/OAIReplacement/index.tsx
- static/img/logos/cortex-logo-mark.svg
> fix: cortex logo mark

- static/huggingface/hub.json
> chore: change owner name to author

- docs/model-operations.mdx
- Update Model Operations
- Closes #
- Closes #
> Update Model Operations

- docusaurus.config.ts
- src/components/OAICoverage/index.tsx
- src/pages/models.tsx
- src/utils/index.ts
> fix: missing list model

- static/huggingface/hub.json
> chore: update logo url

- docs/basic-usage/command-line.md
- docs/built-in-models.mdx
- docs/cli/cortex.md
- docs/formats/gguf.mdx
- docs/formats/onnx.mdx
- docs/formats/tensorrt-llm.mdx
- docs/installation/linux.mdx
- docs/model-yaml.mdx
- docs/overview.mdx
- sidebars.ts
- built-in models
- model.yaml
- Closes #
- Closes #
> Update built-in models and model.yaml

- src/containers/Homepage/OAIReplacement/index.tsx
> enhance: update model section cortex website

- docs/hub/cortex-hub.mdx
- docs/hub/hugging-face.mdx
- docs/hub/nvidia-ngc.mdx
- Remove the init command from model repo
- Closes #
- Closes #
> Remove the init command from model repo

- static/huggingface/hub.json
> update download URL

- src/containers/Homepage/OAIReplacement/index.tsx
> fix: update model section

- docs/basic-usage/command-line.md
- docs/basic-usage/server.mdx
- docs/installation/linux.mdx
- docs/installation/mac.mdx
- docs/installation/windows.mdx
- docs/overview.mdx
- docs/using-models.mdx
- sidebars.ts
- Overview
- Installation
- CLI command
- Server
- Closes #
- Closes #
> Update the getting started section

- src/containers/Homepage/HeroSection/index.tsx
> fix: update title and description

- src/containers/Homepage/HeroSection/index.tsx
> chore: update description hero section

- static/huggingface/hub.json
> chore: correct model url with quant

- static/huggingface/hub.json
> chore: Update hub.json

- docs/cortex-llamacpp.mdx
- docs/cortex-onnx.mdx
- docs/cortex-tensorrt-llm.mdx
- Update the architecture pages to include dependencies
- Closes #
- Closes #
> Update the architecture pages to include dependencies

- src/containers/Homepage/HeroSection/index.tsx
> chore: update description hero

- docs/cli/run.md
- static/openapi/jan.json
- Update the API file
- Closes #
- Closes #
> Update the API file

- docs/basic-usage/server.mdx
- docs/chat-completions.mdx
- docs/cli/benchmark.mdx
- docs/cli/chat.md
- docs/cli/engines/index.mdx
- docs/cli/models/index.md
- docs/cli/ps.md
- docs/cli/pull.md
- docs/cli/run.md
- docs/cli/stop.md
- docs/installation/linux.mdx
- docs/using-models.mdx
- Update the CLI
- Update the API examples
- Update the Linux installation
- Closes #
- Closes #
> Update the docs

- docusaurus.config.ts
> fix: social media link

- docs/installation/linux.mdx
- add npm in linux installation
- Closes #
- Closes #
> add npm in linux installation

- docs/cli/cortex.md
- docs/cli/embeddings.mdx
- docs/cli/engines/index.mdx
- docs/cli/pull.md
- docs/cli/run.md
- Update the CLI docs
- Closes #
- Closes #
> Update the CLI docs

- docusaurus.config.ts
- package.json
- src/styles/apiReference.scss
- src/styles/main.scss
- static/openapi/jan.json
- yarn.lock
> Update the CLI Reference (added the categorization)

- docusaurus.config.ts
> fix: update career link

- docs/overview.mdx
- docs/quickstart.mdx
- Added the built-in model section
- Closes #
- Closes #
> Added the built-in model section

- static/openapi/jan.json
> Updated the API base URL

- docusaurus.config.ts
- package.json
- yarn.lock
> fix: downgrade scalar package

- static/huggingface/hub.json
Replace old model with Gemma2-2b-Instruct in Quickstart model
-
- Closes #
- Closes #
> Update model Small+Smart to Gemma2-2B

- src/pages/models.tsx
> fix: responsive my model

- docs/integrate-remote-engine.mdx
- sidebars.ts
- add how to integrate remote engine page
- Closes #
- Closes #
> feat: add how to integrate remote engine page

- docs/architecture.md
- docs/benchmarking-architecture.mdx
- docs/cortex-onnx.mdx
- docs/cortex-tensorrt-llm.mdx
- docs/telemetry-architecture.mdx
- Update the Runtime to use mermaid.js
- Closes https://github.com/janhq/cortex.so/issues/179
- Closes #
> Update the Runtime to use mermaid.js

- docs/model-yaml.mdx
- fix double note
- Closes #
- Closes #
> fix double note

- docs/cli/chat.md
- docs/cli/cortex.md
- docs/cli/engines/index.mdx
- docs/cli/models/index.md
- docs/cli/ps.md
- docs/cli/pull.md
- docs/cli/run.md
- docs/cli/stop.md
- Update the CLI commands
- Closes #
- Closes #
> Update the CLI commands

- docs/basic-usage/command-line.md
- docs/basic-usage/cortexrc.mdx
- docs/basic-usage/overview.mdx
- docs/cli/chat.mdx
- docs/cli/cortex.md
- docs/cli/cortex.mdx
- docs/cli/embeddings.mdx
- docs/cli/engines/index.mdx
- docs/cli/models/index.mdx
- docs/cli/ps.mdx
- docs/cli/pull.mdx
- docs/cli/run.mdx
- docs/cli/serve.md
- docs/cli/stop.mdx
- docs/cli/update.mdx
- docs/data-folder.mdx
- docs/hub/cortex-hub.mdx
- docs/hub/hugging-face.mdx
- docs/installation/linux.mdx
- docs/installation/mac.mdx
- docs/installation/windows.mdx
- docs/overview.mdx
- docs/quickstart.mdx
- docs/troubleshooting.mdx
- sidebars.ts
- Datafolder cortexrc
- Closes https://github.com/janhq/cortex.cpp/issues/1243
- Closes #
> docs: Update Data Folder and cortexrc file

- docusaurus.config.ts
- src/containers/Homepage/HeroSection/index.tsx
- src/containers/Homepage/SimpleHeroSection/index.tsx
- Changelog to left align
- remove Self-hosted alternative to OpenAI Platform
> chore: remove OpenAI compatible, changelog to left

- docusaurus.config.ts
- static/openapi/jan.json
- Using relative path so that local can test it as well
- Update latest `Engine` apis
> fix: update engine install api

- docs/basic-usage/command-line.md
- docs/basic-usage/cortexrc.mdx
- docs/basic-usage/server.mdx
- docs/chat-completions.mdx
- docs/embeddings.mdx
- docs/quickstart.mdx
- docs/troubleshooting.mdx
- docs/using-models.mdx
- Change port from `3928` to `39281`
- Closes #
- Closes #
> fix: change server default port

- src/components/DropdownDownload/index.tsx
> fix: update link download
